#Copyright Florian Goujeon 2021 - 2025.
#Distributed under the Boost Software License, Version 1.0.
#(See accompanying file LICENSE or copy at
#https://www.boost.org/LICENSE_1_0.txt)
#Official repository: https://github.com/fgoujeon/maki

version: 1.0.{build}

image:
  - Visual Studio 2022

platform:
  - Win32
  - x64

configuration:
  - Release
  - Debug

install:
  - vcpkg install catch2:x64-windows
  - vcpkg install catch2:x86-windows

before_build:
  - cmake -DMAKI_BUILD_TESTS=1 -DMAKI_BUILD_EXAMPLES=1 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -A%PLATFORM% .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - ctest --verbose -C %CONFIGURATION%
